### ISSUE TITLE
v1.4.14 on hex.pm broken?

### ISSUE THREAD

**Issue by aseigo** [alfert/coverex#42]
There is a version 1.4.14 for coverex published on hex.pm, however when pulling that into a project, it fails to compile .. the deps directory ends up being empty!

Pinning the version to 1.4.13 works, however.

Also, there is no 1.4.14 release (or any release after 1.4.10?) in the git repository .. is this intentional?

Cheers, and thanks for the nice library!

**Comment by alfert** [comment]
Ouch. You are right, it does not compile for me as well: The hex archive contains only the README.md, CHANGELOG.md and LICENSE files. I must have done something stupid. 

The missing release are not intentional. The labels are there, so you can construct the source code base of each release. But I simply forgot to manually create the release entries in GitHub, the other part of the release process is automated.

**Comment by alfert** [comment]
The hex package is not retired.

**Comment by aseigo** [comment]
Thanks for the quick response! Sorry I didn't submit a PR myself, just didn't have the time at that moment. Again: thanks! :) Looking forward to the next release ...
